# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2026 Bailey Harrison (baileyharrison04@outlook.com)

PACKAGE_NAME="@_PKGBASE@"
PACKAGE_VERSION="@PKGVER@"
BUILT_MODULE_NAME[0]="@_PKGBASE@"
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb/misc"
AUTOINSTALL="yes"
